[package]
name = "aries-agent-rs"
version = "0.1.0"
edition = "2018"
authors = ["Absa Group Limited", "Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
description = "Sample Aries agent based on aries-vcx library."

[dependencies]
actix-web = "3.0.0"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
log = "0.4"
env_logger = "0.8.1"
once_cell = "1.5.2"
libvcx = { path = "../../../libvcx" }
