name: CI

on:
  push:
    branches:
      - "**"

jobs:
  test-:
    runs-on: macos-10.15
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Switch to xcode version 11
      run: |
        sudo xcode-select --switch /Applications/Xcode_11.7.app/Contents/Developer
        xcodebuild -version
    - name: Build iOS wrapper
      run: |
          ./wrappers/ios/ci/build.sh
